### ISSUE TITLE
Extra lines in tmux.conf

### ISSUE THREAD

**Issue by skovtunenko** [preslavmihaylov/dotfiles#1]
Hello, 
I copied your `tmux.conf` and started using it, and then I realized that there are extra lines in the config that can be removed:
https://github.com/PreslavMihaylov/dotfiles/blob/master/tmux.conf#L16-L50

They will be overridden by the latter config lines. 

Thank you!

**Comment by presmihaylov** [comment]
Thank you for the report.

The redundant lines have been removed as of https://github.com/PreslavMihaylov/dotfiles/commit/51456cec0573aa2f6a096f568baf67c600209465
